### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by ghost**
Updated CMakeLists file to remove the "lib" prefix for the shared library

### CODE REVIEW

**Comment by ghost** [comment]
Probably didn't explain my reasoning for this pull request, but when linked dynamically, it produces a `libBoxer.dll` file, however the code in the PR will make it just `Boxer.dll`, which I feel looks tidier in the build directory.

**Comment by aaronmjacobs** [comment]
The "lib" prefix is standard for dynamic libraries on OS X / Linux. When I build Boxer as a shared library on Windows, I don't see the prefix, as expected (it is just built as "Boxer.dll"). Are you using MinGW by chance?

**Comment by ghost** [comment]
Yes, msvc is not my thing

Get Outlook for Android

On Sun, May 22, 2016 at 2:25 AM -0700, "Aaron Jacobs" notifications@github.com wrote:

The "lib" prefix is standard for dynamic libraries on OS X / Linux. When I build Boxer as a shared library on Windows, I don't see the prefix, as expected (it is just built as "Boxer.dll"). Are you using MinGW by chance?

---

**Comment by aaronmjacobs** [comment]
I believe that the lib prefix is normally expected when using MinGW. In the interest of consistency, I would prefer to not change that behavior, but thanks for the suggestion!

**Pull request closed without merging**
